### ISSUE TITLE
Divshot login hangs at "Logging into Divshot"

### ISSUE THREAD

**Issue by zackify** [divshot/divshot-cli#129]
Nothing happens after typing `divshot login`

![screen shot 2014-10-22 at 2 37 10 pm](https://cloud.githubusercontent.com/assets/449136/4744804/9c38d726-5a33-11e4-9202-85fb91a618d7.png)

**Comment by telardil** [comment]
this command run the default browser in your system. 'ps -A' showed me that that it was w3m. After removing this browser, divshot init show me auth link

**Comment by scottcorgan** [comment]
Sounds good.

If auth is hanging, it's mostly likely a 3rd party application issue. I'll close the issue for now, but continue to add 3rd party apps that block Divshot http calls.

Thanks everyone.
