### ISSUE TITLE
On Windows, Divshot server fails to run with error

### ISSUE THREAD

**Issue by fastdivision** [divshot/divshot-cli#139]
When I attempt to run `divshot server` on Windows, I get the following error:

```
Error: There was an unexexpted error with the server. Perhaps the port is already in use.
```

No instances of `divshot server` were running so the port wasn't in use. Another user reported that a couple of seconds passed and there were no error messages. This is on Divshot CLI 1.4.3.

**Comment by fastdivision** [comment]
This issue appears to be directly related to the CLI and not Superstatic. The latest version of SS works correctly on Windows.

**Comment by scottcorgan** [comment]
Ah, yes, the good 'ol windows child process bug I'll get this fixed asap.

**Comment by scottcorgan** [comment]
@fastdivision What version of Node and NPM is the user using?

**Comment by fastdivision** [comment]
@scottcorgan I could reproduce this on my virtual machine. Using Node v0.10.28 and NPM 1.4.9

**Comment by scottcorgan** [comment]
@fastdivision I'm unable to recreate. Can you try again and post a screenshot?

![screen shot 2015-01-06 at 8 59 57 am](https://cloud.githubusercontent.com/assets/974723/5632290/6cba3776-9582-11e4-8253-1e23a62f8b56.png)

**Comment by fastdivision** [comment]
@scottcorgan Here's a screenshot:

![screen shot 2015-01-06 at 9 08 45 am](https://cloud.githubusercontent.com/assets/1137184/5632459/d3ab6c1a-9583-11e4-953c-09a57c321f1d.png)
