### ISSUE TITLE
Typo on "Get Started" page?

### ISSUE THREAD

**Issue by RickCarlino** [divshot/divshot-cli#141]
Hi,

I just started using Divshot CLI today and was going through [this tutorial](https://dashboard.divshot.com/apps) when tragedy struck:

```
$ divshot config:add name -boiler
Error: Config value for key is required.
```
(Notice the `-` after the name, as seen in the tutorial)
...but when I did it this way...
```
$ divshot config:add name boiler

Config value added
```
Was this a typo, or an error on my part?

**Comment by kevinchau** [comment]
Hi Rick,

Looks like there was just a rendering issue - your divshot username is supposed to appear before the " - "

We'll take a look at why that happened.

**Comment by uptownnickbrown** [comment]
Ran into this same issue today, Google led me here. Thought you might want to know the rendering issue is still out there (I see this ticket was closed).

Adding a username before the "-" of course fixed the issue.

**Comment by fastdivision** [comment]
Thanks @uptownnickbrown! We have a fix on staging but it isn't deployed to production yet. Should be working shortly.
