### ISSUE TITLE
Error: directory does not exist, on CI server, with -c

### ISSUE THREAD

**Issue by dukedave** [divshot/divshot-cli#155]
Per your [Codeship integration instructions](http://docs.divshot.com/integrations/codeship) I have the following as my deploy script:

    push staging --token $DIVSHOT_TOKEN -c divshot.staging.json

However the presence of the `-c` switch is causing:

    Error: directory does not exist

It  works locally on my machine, and it does work on Codeship without the `-c` switch.
Could #112 be related?

**Comment by kevinchau** [comment]
Hey Dave,

Others have done the same thing using Travis just fine.

`divshot -c divshot.staging.json -t $DIVSHOT_TOKEN push staging`

See if that works

**Comment by dukedave** [comment]
Hmm, well that's something @kevinchau, unfortunately it that yields the same error.

And it gets worse, it appears to not work even without the `-a` switch.
I'm not sure how I missed that originally :unamused:

**Comment by kevinchau** [comment]
What does your divshot.staging.json look like?

**Comment by dukedave** [comment]
See here @kevinchau: https://gist.github.com/dukedave/7d0b55dcc762fdd9f280

**Comment by kevinchau** [comment]
So there's something going on with your root directory. Either Codeship isn't building your app properly, or there's something weird with the syntax. try add `ls` between the build process and the deploy process to see what it spits out.

**Comment by dukedave** [comment]
Ha, well that's embarrassing, I forgot to do the build step :laughing: 

I suppose I could possibly argue that the error should say, e.g. `Error: root directory specified in config file does not exist`, but it's still user error!.
